### ISSUE TITLE
Add Scribble

### ISSUE THREAD

**Issue by GNSPS** [leonardoalt/ethereum_formal_verification_overview#13]
Not really "formal" verification. But a good endeavor in making property verification easy for developers.

Maybe think about adding https://docs.scribble.codes to the list? 😊 🙌

**Comment by leonardoalt** [comment]
Sure! Can you please push a PR adding it under `Solidity` with a small description you'd like to have and links/material?

**Comment by leonardoalt** [comment]
Added!

**Comment by GNSPS** [comment]
Thank you, @leonardoalt!! And sorry for not doing it! Super crazy last few days! 🙏
