### ISSUE TITLE
Add entry in section EVM – EVM in Dafny and related items

### ISSUE THREAD

**Issue by franck44** [leonardoalt/ethereum_formal_verification_overview#19]
The have developed a formal and executable semantics of the EVM in Dafny.
It is available in this repo: https://github.com/Consensys/evm-dafny

There is a paper at FM'23 presenting the main contributions:

- [FM paper](https://link.springer.com/chapter/10.1007/978-3-031-27481-7_32)
- [ArXiv version](https://arxiv.org/abs/2303.00152)

**Comment by leonardoalt** [comment]
Nice! Could you please open a PR?

**Comment by xerath7d0** [comment]
I've opened a PR for this issue. Please see https://github.com/leonardoalt/ethereum_formal_verification_overview/pull/20#issue-2008983078
