### ISSUE TITLE
Add VeriSol to Solidity formal verifiers

### ISSUE THREAD

**Issue by shuvendu-lahiri** [leonardoalt/ethereum_formal_verification_overview#5]
Hi, we have been making progress towards supporting formal specifications and highly automated and scalable verification/falsification for Solidity smart contracts in VeriSol project https://github.com/Microsoft/verisol. Happy to create a PR with the update to README.md if you feel it is in scope. Thanks!

**Comment by leonardoalt** [comment]
Hi @shuvendu-lahiri , that's great!
Yes, it'd be great if you could open a PR updating the list accordingly: target, sorted alphabetically, containing relevant links to papers, presentations, articles.
